In [4]:
import pandas as pd
import requests
import io
import urllib3
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

In [21]:
url = "https://www.rba.gov.au/statistics/tables/csv/g4-data.csv"
response = requests.get(url, verify=False)
df_cpi = pd.read_csv(io.StringIO(response.text), skiprows=11, names=['date', 'cpi_index', 'yoy_inflation', 'monthly_change_original', 'monthly_change_seasonally_adjusted'])
df_cpi.head(10)

,date,cpi_index,yoy_inflation,monthly_change_original,monthly_change_seasonally_adjusted
0,30/04/2024,96.40,NaN,NaN,NaN
1,31/05/2024,96.17,NaN,-0.2,0.3
2,30/06/2024,96.52,NaN,0.4,0.4
3,31/07/2024,96.77,NaN,0.3,-0.1
4,31/08/2024,96.49,NaN,-0.3,0.0
5,30/09/2024,96.54,NaN,0.1,-0.2
6,31/10/2024,96.32,NaN,-0.2,0.1
7,30/11/2024,96.68,NaN,0.4,0.6
8,31/12/2024,97.31,NaN,0.7,0.0
9,31/01/2025,97.58,NaN,0.3,0.5

In [ ]:
print(df_cpi['date'].min())  
print(df_cpi['date'].max())
print(df_cpi.shape)

In [23]:
df_cpi.tail(15)

,date,cpi_index,yoy_inflation,monthly_change_original,monthly_change_seasonally_adjusted
12,30/04/2025,98.68,2.4,0.7,0.2
13,31/05/2025,98.20,2.1,-0.5,0.0
14,30/06/2025,98.34,1.9,0.1,0.1
15,31/07/2025,99.63,3.0,1.3,0.9
16,31/08/2025,99.55,3.2,-0.1,0.2
17,30/09/2025,100.00,3.6,0.5,0.3
18,31/10/2025,99.99,3.8,0.0,0.4
19,30/11/2025,100.01,3.4,0.0,0.2
20,31/12/2025,100.97,3.8,1.0,0.2
21,31/01/2026,101.33,3.8,0.4,0.5
22,28/02/2026,101.31,3.7,0.0,0.2
23,31/03/2026,102.44,4.6,1.1,1.1
24,30/04/2026,NaN,NaN,NaN,NaN
25,31/05/2026,NaN,NaN,NaN,NaN
26,30/06/2026,NaN,NaN,NaN,NaN

In [9]:
df_cpi.describe()

       G4 CONSUMER PRICE INFLATION – MONTHLY COLLECTION
count                                                31
unique                                               19
top                                                 0.2
freq                                                  5

In [10]:
df_cpi.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 35 entries, ('Title', 'Consumer price index', 'Year-ended inflation', 'Monthly inflation – original') to ('30/06/2026', nan, nan, nan)
Data columns (total 1 columns):
 #   Column                                            Non-Null Count  Dtype
---  ------                                            --------------  -----
 0   G4 CONSUMER PRICE INFLATION – MONTHLY COLLECTION  31 non-null     object
dtypes: object(1)
memory usage: 4.5+ KB

In [12]:
print(response.text[:1000])

G4 CONSUMER PRICE INFLATION – MONTHLY COLLECTION
Title,Consumer price index,Year-ended inflation,Monthly inflation – original,Monthly inflation
Description,Consumer price index; All groups,Consumer price index; All groups; Year-ended change (in per cent),Consumer price index; All groups; Original; Monthly change (in per cent),Consumer price index; All groups; Monthly change (in per cent)
Frequency,Monthly,Monthly,Monthly,Monthly
Type,Original,Original,Original,Seasonally adjusted
Units,"Index, September 2025 = 100",Per cent,Per cent,Per cent


Source,ABS,ABS,ABS,ABS
Publication date,30-Apr-2026,30-Apr-2026,30-Apr-2026,30-Apr-2026
Series ID,GCPIAGM,GCPIAGYPM,GCPIAGMP,GCPIAGSAMP
30/04/2024,96.40
31/05/2024,96.17,,-0.2,0.3
30/06/2024,96.52,,0.4,0.4
31/07/2024,96.77,,0.3,-0.1
31/08/2024,96.49,,-0.3,0.0
30/09/2024,96.54,,0.1,-0.2
31/10/2024,96.32,,-0.2,0.1
30/11/2024,96.68,,0.4,0.6
31/12/2024,97.31,,0.7,0.0
31/01/2025,97.58,,0.3,0.5
28/02/2025,97.67,,0.1,0.3
31/03/2025,97.96,,0.3,0.3
30/04/

In [35]:
url_g1 = "https://www.rba.gov.au/statistics/tables/csv/g1-data.csv"  
response_g1 = requests.get(url_g1, verify=False)
print(response_g1.text[4000:5500])
df_cpi_g1 = pd.read_csv(io.StringIO(response_g1.text), skiprows=10, usecols=[0, 10, 20], header=None, names=['date', 'trimmed_mean_yoy', 'trimmed_mean_quarterly'])
df_cpi_g1 = df_cpi_g1.iloc[1:]
df_cpi_g1.head(10)

,Original,Original,Seasonally adjusted,Seasonally adjusted,Original,Seasonally adjusted,Seasonally adjusted,Seasonally adjusted,Seasonally adjusted,Seasonally adjusted,Seasonally adjusted,Seasonally adjusted,Seasonally adjusted,Seasonally adjusted
Units,"Index, September 2025 month = 100",Per cent,Per cent,Per cent,Per cent,Per cent,Per cent,Per cent,Per cent,Per cent,Per cent,Per cent,Per cent,Per cent,Per cent,Per cent,Per cent,Per cent,Per cent,Per cent


Source,ABS / RBA,ABS / RBA,ABS / RBA,RBA,RBA,RBA,RBA,RBA,ABS / RBA,ABS / RBA,ABS / RBA,ABS / RBA,ABS / RBA,RBA,RBA,RBA,RBA,RBA,ABS / RBA,ABS / RBA
Publication date,30-Apr-2026,30-Apr-2026,30-Apr-2026,30-Apr-2026,30-Apr-2026,30-Apr-2026,30-Apr-2026,30-Apr-2026,30-Apr-2026,30-Apr-2026,30-Apr-2026,30-Apr-2026,30-Apr-2026,30-Apr-2026,30-Apr-2026,30-Apr-2026,30-Apr-2026,30-Apr-2026,30-Apr-2026,30-Apr-2026
Series ID,GCPIAG,GCPIAGYP,GCPIEITCYP,GCPIXVIYP,GCPITIYP,GCPITXVIYP,GCPINTIYP,GCPINTXDLYP,GCPIOCPMWMYP,GCPIOCPMTMYP,GCPIAGQP,GCPIAGSAQP,GCPIEITCQP,GCPIXVIQP,GCPITIQP,GCPITXVIQP,GCPINTIQP,GCPINTXDLQP,GCPIOCPMWMQP,GCPIOCPMTMQP
30/06/1922,1.93
30/09/1922,1.93,,,,,,,,,,-0.1
31/12/1922,1.91,,,,,,,,,,-1.1
31/03/1923,1.92,,,,,,,,,,0.4
30/06/1923,1.98,2.3,2.3,,,,,,,,3.1
30/09/1923,2.00,3.8,3.8,,,,,,,,1.4
31/12/1923,2.00,4.6,4.6,,,,,,,,-0.4
31/03/1924,1.94,1.4,1.4,,,,,,,,-2.6
30/06/1924,1.94,-1.7,-1.7,,,,,,,,0.0
30/09/1924,1.93,-3.7,-3.7,,,,,,,,-0.8
31/12/1924,1.93,-3.3,-3.3,,,,,,,,0.0
31/03/1925,1.96,0.8,0.8,,,,,,,,1.6
30/06/1925,1.98

          date trimmed_mean_yoy trimmed_mean_quarterly
1   30/06/1922              NaN                    NaN
2   30/09/1922              NaN                    NaN
3   31/12/1922              NaN                    NaN
4   31/03/1923              NaN                    NaN
5   30/06/1923              NaN                    NaN
6   30/09/1923              NaN                    NaN
7   31/12/1923              NaN                    NaN
8   31/03/1924              NaN                    NaN
9   30/06/1924              NaN                    NaN
10  30/09/1924              NaN                    NaN

In [36]:
df_cpi_g1.tail(10)

           date trimmed_mean_yoy trimmed_mean_quarterly
410  30/09/2024              3.6                    0.8
411  31/12/2024              3.3                    0.5
412  31/03/2025              2.9                    0.7
413  30/06/2025              2.7                    0.7
414  30/09/2025              3.0                    1.0
415  31/12/2025              3.4                    0.9
416  31/03/2026              3.5                    0.8
417  30/06/2026              NaN                    NaN
418  30/09/2026              NaN                    NaN
419  31/12/2026              NaN                    NaN

In [38]:
df_cpi_g1[df_cpi_g1['trimmed_mean_yoy'].notna()].head()

           date trimmed_mean_yoy trimmed_mean_quarterly
244  31/03/1983             10.7                    2.2
245  30/06/1983             10.0                    1.8
246  30/09/1983              8.5                    1.5
247  31/12/1983              7.9                    2.1
248  31/03/1984              7.0                    1.4

In [39]:
df_cpi_g1.dtypes

date                      object
trimmed_mean_yoy          object
trimmed_mean_quarterly    object
dtype: object

In [49]:
url_h5 = "https://www.rba.gov.au/statistics/tables/csv/h5-data.csv"  
response_h5 = requests.get(url_h5, verify=False)
print(response_h5.text[:2000])
df_labour_force_h5 = pd.read_csv(io.StringIO(response_h5.text), skiprows=10, usecols=[0,10,11], names=['date','unemployed_%', 'unemployed_trend'])
df_labour_force_h5 = df_labour_force_h5.iloc[1:]
df_labour_force_h5.head(10)
df_labour_force_h5.tail(10)

H5 LABOUR FORCE
Title,Labour force,Participation rate,Part-time employment,Full-time employment,Employment,Year-ended employment growth,Year-ended employment trend growth,Employment to population ratio,Unemployment,Unemployment rate,Unemployment rate trend,Hours worked,Hours worked trend,Year-ended hours worked trend growth,Average hours worked trend,Job vacancies,Private sector job vacancies,Vacancies to labour force ratio
Description,Labour force persons,Labour force participation rate,Part-time employed persons,Full-time employed persons,Employed persons,Employed persons; Year-ended change (in per cent),Employed persons; Trend; Year-ended change (in per cent),Employed persons as percentage of working age civilian population,Unemployed persons,Unemployed persons as percentage of labour force,Unemployed persons as percentage of labour force; Trend,Total hours worked per month,Total hours worked per month; Trend,Total hours worked per month; Trend; Year-ended change (in per cent),Average hours worked per week,Number of job vacancies,Number of job vacancies in private sector,Job vacancies as percentage of labour force
Frequency,Monthly,Monthly,Monthly,Monthly,Monthly,Monthly,Monthly,Monthly,Monthly,Monthly,Monthly,Monthly,Monthly,Monthly,Monthly,Quarterly,Quarterly,Quarterly
Type,Seasonally adjusted,Seasonally adjusted,Seasonally adjusted,Seasonally adjusted,Seasonally adjusted,Seasonally adjusted,Trend,Seasonally adjusted,Seasonally adjusted,Seasonally adjusted,Trend,Seasonally adjusted,Trend,Trend,Trend,Seasonally adjusted,Seasonally adjusted,Seasonally adjusted
Units,'000,Per cent,'000,'000,'000,Per cent,Per cent,Per cent,'000,Per cent,Per cent,'000,'000,Per cent,Hours,'000,'000,Per cent


Source,ABS,ABS,ABS,ABS,ABS,ABS,ABS,ABS,ABS,ABS,ABS,ABS,ABS,ABS,ABS,ABS,ABS,ABS
Publication date,17-Apr-2026,17-Apr-2026,17-Apr-2026,17-Apr-2026,17-Apr-2026,17-Apr-2026,17-Apr-2026,17-Apr-2026,17-Apr-2026,17-Apr-2026,17-Apr-2026,17-Apr-2026,17-Apr-2026,17-Apr-2026,17-Apr-2026,07-

           date unemployed_% unemployed_trend
572  30/09/2025          4.5              4.3
573  31/10/2025          4.3              4.3
574  30/11/2025          4.3              4.3
575  31/12/2025          4.1              4.3
576  31/01/2026          4.1              4.3
577  28/02/2026          4.3              4.3
578  31/03/2026          4.3              4.3
579  30/04/2026          NaN              NaN
580  31/05/2026          NaN              NaN
581  30/06/2026          NaN              NaN

In [55]:
url_i2 = "https://www.rba.gov.au/statistics/tables/csv/i2-data.csv"  
response_i2 = requests.get(url_i2, verify=False)
print(response_i2.text[:5000])
df_commodity_i2 = pd.read_csv(io.StringIO(response_i2.text), skiprows=10, usecols=[0,1,3,13,15], names=['date','overall_AU$', 'overall_US$', 'bulk_AU$','bulk_US$'])
df_commodity_i2 = df_commodity_i2.iloc[1:]
df_commodity_i2.head(10)
df_commodity_i2.tail(10)

I2 COMMODITY PRICES
Title,Commodity prices – A$,Commodity prices – SDR,Commodity prices – US$,Rural commodity prices – A$,Rural commodity prices – SDR,Rural commodity prices – US$,Non-rural commodity prices – A$,Non-rural commodity prices – SDR,Non-rural commodity prices – US$,Base metals prices – A$,Base metals prices – SDR,Base metals prices – US$,Bulk commodities prices – A$,Bulk commodities prices – SDR,Bulk commodities prices – US$,Commodity prices (with bulk commodities spot prices) – A$,Commodity prices (with bulk commodities spot prices) – SDR,Commodity prices (with bulk commodities spot prices) – US$,Bulk commodities spot prices – A$,Bulk commodities spot prices – SDR,Bulk commodities spot prices – US$
Description,Index of commodity prices; All items; A$,Index of commodity prices; All items; SDR,Index of commodity prices; All items; US$,Index of commodity prices; Rural component; A$,Index of commodity prices; Rural component; SDR,Index of commodity prices; Rural component; US$,Index of commodity prices; Non-rural component; A$,Index of commodity prices; Non-rural component; SDR,Index of commodity prices; Non-rural component; US$,Index of commodity prices; Non-rural component – Base metals; A$,Index of commodity prices; Non-rural component – Base metals; SDR,Index of commodity prices; Non-rural component – Base metals; US$,Index of commodity prices; Non-rural component – Bulk commodities (based on export price movements); A$,Index of commodity prices; Non-rural component – Bulk commodities (based on export price movements); SDR,Index of commodity prices; Non-rural component – Bulk commodities (based on export price movements); US$,Index of commodity prices; All items (with bulk commodities spot prices); A$,Index of commodity prices; All items (with bulk commodities spot prices); SDR,Index of commodity prices; All items (with bulk commodities spot prices); US$,Index of commodity prices; Non-rural component – Bulk commodities (based on spot price movements); A$,Index of commodity prices; Non-rural component – Bulk commodities (based on spot price movements); SDR,Index of commodity prices; Non-rural component – Bulk commodities (based on spot price movements); US$
Frequency,Monthly,Monthly,Monthly,Monthly,Monthly,Monthly,Monthly,Monthly,Monthly,Monthly,Monthly,Monthly,Monthly,Monthly,Monthly,Monthly,Monthly,Monthly,Monthly,Monthly,Monthly
Type,Original,Original,Original,Original,Original,Original,Original,Original,Original,Original,Original,Original,Original,Original,Original,Original,Original,Original,Original,Original,Original
Units,"Index, 2024/25=100","Index, 2024/25=100","Index, 2024/25=100","Index, 2024/25=100","Index, 2024/25=100","Index, 2024/25=100","Index, 2024/25=100","Index, 2024/25=100","Index, 2024/25=100","Index, 2024/25=100","Index, 2024/25=100","Index, 2024/25=100","Index, 2024/25=100","Index, 2024/25=100","Index, 2024/25=100","Index, 2024/25=100","Index, 2024/25=100","Index, 2024/25=100","Index, 2024/25=100","Index, 2024/25=100","Index, 2024/25=100"


Source,RBA,RBA,RBA,RBA,RBA,RBA,RBA,RBA,RBA,RBA,RBA,RBA,RBA,RBA,RBA,RBA,RBA,RBA,RBA,RBA,RBA
Publication date,01-May-2026,01-May-2026,01-May-2026,01-May-2026,01-May-2026,01-May-2026,01-May-2026,01-May-2026,01-May-2026,01-May-2026,01-May-2026,01-May-2026,01-May-2026,01-May-2026,01-May-2026,01-May-2026,01-May-2026,01-May-2026,01-May-2026,01-May-2026,01-May-2026
Series ID,GRCPAIAD,GRCPAISDR,GRCPAIUSD,GRCPRCAD,GRCPRCSDR,GRCPRCUSD,GRCPNRAD,GRCPNRSDR,GRCPNRUSD,GRCPBMAD,GRCPBMSDR,GRCPBMUSD,GRCPBCAD,GRCPBCSDR,GRCPBCUSD,GRCPAISAD,GRCPAISSDR,GRCPAISUSD,GRCPBCSAD,GRCPBCSSDR,GRCPBCSUSD
31/07/1982,22.1,41.5,34.5,34.7,65.0,54.1,21.2,39.9,33.2,17.0,32.0,26.6,22.9,43.0,35.8
31/08/1982,22.3,41.3,33.8,34.3,63.7,52.0,21.7,40.3,32.9,17.3,32.0,26.2,23.0,42.7,34.9
30/09/1982,23.1,42.2,34.3,35.0,63.9,51.9,22.9,41.7,33.9,17.3,31.7,25.7,23.6,43.1,35.0
31/10/1982,23.4,42.4,34.1,35.5,64.3,51.8,23.0,41.7,33.6,17.3,31.4,25.2,24.0,43.5,35.0
30/11/1982,23.4,42.6,34.1,35.6,64.6,51.7,23.1,41.9,33.6,16.6,30.2,24.2,24.4,44.3,35.5
31/12/1982,23.0,41.9,34.4,34.7,63.3,51.9,22.8,41.4,34.0,16.1,29.4,24.1,23.8,43.3,35.6
31/01/1983,23.2,42.6,35.2,34.5,63.3,52.3,23.2,42.5,35.2,17.0,31.2,25.8,23.8,43.6,36.0
28/02/1983,23.8,43.4,35.5,35.6,65.0,53.2,23.6,43.1,35.3,18.1,33.1,27.1,23.8,43.4,35.6
31/03/1983,25.1,42.0,34.2,39.1,65.5,53.4,24.2,40.5,33.0,20.3,34.0,27.8,24.5,41.0,33.5
30/04/1983,25.6,42.1,34.3,40.9,67.4,54.7,24.2,39.9,32.5,21.4,35.2,28.6,23.9,39.4,32.1
31/05/1983,25.5,42.6,34.7,41.7,69.6,56.6,23.8,39.7,32.3,21.9,36.5,29.7,23.1,38.5,31.4
30/06/1983,25.4,42.8,34.4,42.2,71.2,57.1,23.3,39.3,31.6,21.5,36.2,29.1,22.8,38.5,30.9
31/07/1983,25.2,42.6,34.0,41.6,70.4,56.3,23.2,39.2,31.4,21.8,36.9,29.5,22.4,37.9,30.3
31/08/1983,25.4,43.7,34.5,41.8,71.9,56.8,23.5,40.4,31.9,22.3,38.3,30.2,22.8,39.2,31.0
30/09/1983,24.8,43.1,34.0,41.0,71.2,56.2,22.9,39.8,31.4,22.1,38.4,30.3,22.1,38.4,30.3
31/10/1983,24.2,42.9,34.2,40.2,71.1,56.7,22.3,39.4,31.5,21.0,37.2,29.7,21.9,38.8,31.0
30/11/1983,23.6,

           date overall_AU$ overall_US$ bulk_AU$ bulk_US$
520  31/10/2025       102.0       103.1     97.1     98.2
521  30/11/2025       103.5       104.1     97.2     97.7
522  31/12/2025       102.8       105.5     96.1     98.7
523  31/01/2026       104.7       109.6     96.1    100.6
524  28/02/2026       102.0       111.2     92.1    100.3
525  31/03/2026       105.0       114.0     95.9    104.0
526  30/04/2026       104.2       113.8     95.6    104.4
527  31/05/2026         NaN         NaN      NaN      NaN
528  30/06/2026         NaN         NaN      NaN      NaN
529  31/07/2026         NaN         NaN      NaN      NaN